export const dummyData02 = {
  unitType: 'DELIVERY_GUIDE_02',
  pageSetId: '78',
  reactPrefix: '홈|배송시간안내(최상단)|',
  shpplocListUrl: '#',
  foldBtnTxt: '지금 주문하면',
  dataType: 'DELIVERY',
  shpplocListBtnTxt: '배송지 변경',
  pageId: '100000000017',
  tareaCd: '100000000017_78_107',
  shppTimeList: [
    {
      msgNoColorSecond: '',
      shppTime: '오늘 16시~19시까지 emart 쓱배송',
      siteNo: '6001',
      msgNoColorFirst: '까지 ',
      msgColorFirst: '오늘 16시~19시',
      msgColorSecond: 'emart 쓱배송',
      lnkdUrl: '#',
      msgColrCdVal: '#ffd000',
      siteName: 'emart',
    },
    {
      msgNoColorSecond: '',
      shppTime: '내일 ~06시까지 새벽배송',
      siteNo: '7009',
      msgNoColorFirst: '까지 ',
      msgColorFirst: '내일 ~06시',
      msgColorSecond: '새벽배송',
      lnkdUrl: '#',
      msgColrCdVal: '#a3b7cd',
      siteName: 'earlymorning',
    },
    {
      msgNoColorSecond: '',
      shppTime: '내일 ~10시까지 트레이더스 쓱배송',
      siteNo: '6002',
      msgNoColorFirst: '까지 ',
      msgColorFirst: '내일 ~10시',
      msgColorSecond: '트레이더스',
      lnkdUrl: '#',
      msgColrCdVal: '#99cc00',
      siteName: 'traders',
    },
  ],
  pageCmptId: '107',
};
