export const videoRollingBannerDummyData = [
  {
    id: '2002854427',
    title: '10/18 쓱 포레스트',
    desc: '10/18 쓱 포레스트',
    lnkdUrl: 'http://www.ssg.com/event/eventDetail.ssg?promId=1100732422&app_banrId=2002854427',
    lnkdType: '10',
    imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202110/2021101517543244028100114810_852.jpg',
    strtDts: '20211018000000',
    endDts: '20211031235959',
    maiTitleNm1: '',
    maiTitleNm2: '',
    subtitlNm1: '',
    subtitlNm2: '',
    iconTgtLst: '',
    titleShadUseYn: '',
    imgWidth: '750',
    imgHeight: '460',
    dispOrdr: '',
    bakgrndColrCdVal: '',
    banrRplcTextNm: '10/18 쓱 포레스트',
    modDts: '',
    advertYn: '',
    newYn: '',
    soldOutYn: null,
    viewCnt: 0,
    likeCnt: 0,
    dispCtgNm: null,
    ssgOnlyYn: null,
    repItemImgFileNm: null,
    repItemNm: null,
    repItemPrc: null,
    repItemOriPrc: null,
    dtlLnkdUrl: null,
    notiRegUrl: 'http://www.ssg.com/event/eventDetail.ssg?promId=1100732422',
    notiSendYn: null,
    brocItemList: null,
    regTypeCd: '',
    subtlCntt: '',
    dataFileNm: '',
    banrTgtTypeCd: '',
    banrTypeCd: '40',
    advertAcctId: '',
    advertBidId: '',
    advertBilngTypeCd: '',
    advertKindCd: '',
    advertExtensTeryDivCd: '',
    mdlInfo: null,
    banrTagTgtList: null,
    iconTgtList: [],
  },
  {
    id: '2002764756',
    title: '닷컴카드 8월~',
    desc: '닷컴카드 8월~',
    lnkdUrl: 'http://m.ssg.com/event/eventDetail.ssg?promId=1100543537&app_banrId=2002764756',
    lnkdType: '10',
    imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202108/2021080210454333179079709907_92.jpg',
    strtDts: '20210801000000',
    endDts: '20211231235959',
    maiTitleNm1: '',
    maiTitleNm2: '',
    subtitlNm1: '',
    subtitlNm2: '',
    iconTgtLst: '',
    titleShadUseYn: '',
    imgWidth: '750',
    imgHeight: '460',
    dispOrdr: '',
    bakgrndColrCdVal: '',
    banrRplcTextNm: '닷컴카드 8월~',
    modDts: '',
    advertYn: '',
    newYn: '',
    soldOutYn: null,
    viewCnt: 0,
    likeCnt: 0,
    dispCtgNm: null,
    ssgOnlyYn: null,
    repItemImgFileNm: null,
    repItemNm: null,
    repItemPrc: null,
    repItemOriPrc: null,
    dtlLnkdUrl: null,
    notiRegUrl: 'http://m.ssg.com/event/eventDetail.ssg?promId=1100543537',
    notiSendYn: null,
    brocItemList: null,
    regTypeCd: '',
    subtlCntt: '',
    dataFileNm: '',
    banrTgtTypeCd: '',
    banrTypeCd: '40',
    advertAcctId: '',
    advertBidId: '',
    advertBilngTypeCd: '',
    advertKindCd: '',
    advertExtensTeryDivCd: '',
    mdlInfo: null,
    banrTagTgtList: null,
    iconTgtList: [],
  },
  {
    id: '2002764760',
    title: '삼성카드 8월~',
    desc: '삼성카드 8월~',
    lnkdUrl: 'http://m.ssg.com/event/eventDetail.ssg?promId=1100575267&app_banrId=2002764760',
    lnkdType: '10',
    imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202107/2021073016284785953950978395_872.jpg',
    strtDts: '20210801000000',
    endDts: '20211231235959',
    maiTitleNm1: '',
    maiTitleNm2: '',
    subtitlNm1: '',
    subtitlNm2: '',
    iconTgtLst: '',
    titleShadUseYn: '',
    imgWidth: '750',
    imgHeight: '460',
    dispOrdr: '',
    bakgrndColrCdVal: '',
    banrRplcTextNm: '삼성카드 8월~',
    modDts: '',
    advertYn: '',
    newYn: '',
    soldOutYn: null,
    viewCnt: 0,
    likeCnt: 0,
    dispCtgNm: null,
    ssgOnlyYn: null,
    repItemImgFileNm: null,
    repItemNm: null,
    repItemPrc: null,
    repItemOriPrc: null,
    dtlLnkdUrl: null,
    notiRegUrl: 'http://m.ssg.com/event/eventDetail.ssg?promId=1100575267',
    notiSendYn: null,
    brocItemList: null,
    regTypeCd: '',
    subtlCntt: '',
    dataFileNm: '',
    banrTgtTypeCd: '',
    banrTypeCd: '40',
    advertAcctId: '',
    advertBidId: '',
    advertBilngTypeCd: '',
    advertKindCd: '',
    advertExtensTeryDivCd: '',
    mdlInfo: null,
    banrTagTgtList: null,
    iconTgtList: [],
  },
];
