export default {
  shopBannerList: [
    {
      id: '2002296794',
      title: '선물하기',
      desc: '선물하기',
      lnkdUrl: 'http://m.ssg.com/page/gifthome.ssg?app_banrId=2002296794',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015311070169716444081_676.png',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '1',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '선물하기',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002657142',
      title: '공식스토어',
      desc: '공식스토어',
      lnkdUrl: 'http://m.ssg.com/special/index.ssg?app_banrId=2002657142',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015311984385006428600_942.png',
      strtDts: '20210428000000',
      endDts: '99991231235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '2',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '공식스토어',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002729865',
      title: 'SSG.LIVE',
      desc: 'SSG.LIVE',
      lnkdUrl: 'http://m.ssg.com/page/ssglive/main/_v11.ssg?app_banrId=2002729865',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015385604775848505684_980.png',
      strtDts: '20210630170000',
      endDts: '20990630235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '4',
      bakgrndColrCdVal: '',
      banrRplcTextNm: 'SSG.LIVE (New2)',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002296817',
      title: '신상품',
      desc: '신상품',
      lnkdUrl: 'http://m.ssg.com/page/newarrival.ssg?app_banrId=2002296817',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015314706369478213057_746.png',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '5',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '신상품',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002296802',
      title: '프리오더',
      desc: '프리오더',
      lnkdUrl: 'http://m.ssg.com/service/preorder/main.ssg?app_banrId=2002296802',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015321591167517343851_561.png',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '6',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '프리오더',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002296813',
      title: '매거진',
      desc: '매거진',
      lnkdUrl: 'http://m.ssg.com/contents/lifeMagazineMain.ssg?app_banrId=2002296813',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015323602240626641162_764.png',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '8',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '라이프매거진',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002296790',
      title: '우르르',
      desc: '우르르',
      lnkdUrl: 'http://m.ssg.com/service/urr/main.ssg?app_banrId=2002296790',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015324677811469486246_476.png',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '9',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '우르르',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002729159',
      title: '스토어나우',
      desc: '스토어나우',
      lnkdUrl: 'http://m.ssg.com/service/storepost.ssg?app_banrId=2002729159',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021062915583803902030262203_225.png',
      strtDts: '20210629000000',
      endDts: '99991231235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '10',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '스토어나우',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
  ],
  siteNo: '6005',
  specailBrandBannerList: [],
  killerBannerList: [
    {
      id: '2002298823',
      title: 'MONDAY MOON',
      desc: 'MONDAY MOON',
      lnkdUrl: 'http://m.ssg.com/monm/main.ssg?app_banrId=2002298823',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072715042465886006762700_363.jpg',
      strtDts: '20200724000000',
      endDts: '20510724235959',
      maiTitleNm1: 'MONDAY MOON',
      maiTitleNm2: '',
      subtitlNm1: '체험단 혜택부터 리얼 리뷰까지,',
      subtitlNm2: '새로운 뷰티를 만나다.',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '580',
      imgHeight: '348',
      dispOrdr: '0',
      bakgrndColrCdVal: '',
      banrRplcTextNm: 'MONDAY MOON',
      modDts: '20200724163612',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002478751',
      title: '유아동',
      desc: '유아동',
      lnkdUrl: 'http://m.ssg.com/bpage/ssgbaby/main.ssg?app_banrId=2002478751',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202101/2021011217141292420493604049_8.jpg',
      strtDts: '20201214140000',
      endDts: '20511231235959',
      maiTitleNm1: 'Little SSG',
      maiTitleNm2: '',
      subtitlNm1: '파격특가 타임딜과 아이맞춤상품',
      subtitlNm2: '내 아이를 위한 공간',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '850',
      imgHeight: '510',
      dispOrdr: '1',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '유아동',
      modDts: '20210707160847',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
  ],
  themeShopGrid: {
    unitType: 'QUICK_GRID_BANNER',
    reactPrefix: '카테고리_LNB|공식스토어|',
    maiTitleNm1: '공식스토어',
    maiTitleNm2: '전체보기',
    hasNext: 'false',
    lnkdUrl: 'http://m.ssg.com/special/index.ssg',
    pageId: '',
    optionTypes: [],
    banrList: [
      {
        id: '',
        title: '아모레퍼시픽',
        desc: '',
        lnkdUrl:
          'http://m.shinsegaemall.ssg.com/specialStore/brand-amorepacific/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070517031489993038794403_767.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'Y',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'BOSS',
        desc: '',
        lnkdUrl: 'http://m.shinsegaemall.ssg.com/specialStore/boss/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019071014132705547991821899_515.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'Y',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'mybeautybox',
        desc: '',
        lnkdUrl: 'http://m.ssg.com/specialStore/lorealkorea/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202104/2021041912522062188535135953_784.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '베네베네',
        desc: '',
        lnkdUrl:
          'http://m.shinsegaemall.ssg.com/specialStore/benebene/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202106/2021062816381798721262415126_253.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'Y',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '닥스ACC',
        desc: '',
        lnkdUrl:
          'http://m.shinsegaemall.ssg.com/specialStore/daks-acc/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202107/2021071514200351401202542120_350.jpg',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'Y',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '파네라이',
        desc: '',
        lnkdUrl:
          'http://m.shinsegaemall.ssg.com/specialStore/panerai/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202107/2021070817131353816666099666_413.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'Y',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '해즈브로',
        desc: '',
        lnkdUrl:
          'http://m.shinsegaemall.ssg.com/specialStore/hasbro/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202107/2021071509081115596556912755_921.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'Y',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '영실업',
        desc: '',
        lnkdUrl:
          'http://m.shinsegaemall.ssg.com/specialStore/youngtoys/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202107/2021071509074818949352219935_754.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'Y',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '노브랜드',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/nobrand/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070517084893210955207095_101.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '피코크',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/ssgpeacock/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070517090299932787088278_528.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'GUCCI',
        desc: '',
        lnkdUrl: 'http://m.shinsegaemall.ssg.com/special/gucci/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070516574566068848131984_839.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'CHANEL',
        desc: '',
        lnkdUrl: 'http://m.shinsegaemall.ssg.com/special/chanel/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070517033057004042485404_411.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'BURBERRY',
        desc: '',
        lnkdUrl:
          'http://m.shinsegaemall.ssg.com/specialStore/burberry/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070516580460176137153713_687.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '나이키',
        desc: '',
        lnkdUrl: 'http://m.shinsegaemall.ssg.com/specialStore/nike/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201909/2019093014402469349036769903_130.jpg',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'RALPH LAUREN',
        desc: '',
        lnkdUrl:
          'http://m.shinsegaemall.ssg.com/specialStore/ralphlauren/main.ssg?tarea=store6005ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070517045997151193870219_243.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
    ],
    pageCmptId: '',
  },
  ctgList: [
    {
      dispCtgZoneId: '5410000001',
      dispCtgId: null,
      dispCtgNm: '패션',
      dispCtgEnNm: 'Fashion',
      dispCtgZhNm: '时装',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072114390815774221130522_275.jpg',
      linkUrl: 'http://m.ssg.com/page/llcategory/5410000001.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '패션',
    },
    {
      dispCtgZoneId: '1000015891',
      dispCtgId: null,
      dispCtgNm: '잡화',
      dispCtgEnNm: 'Bag/Shoes',
      dispCtgZhNm: '包鞋',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072114393459688641690964_438.jpg',
      linkUrl: 'http://m.ssg.com/page/llcategory/1000015891.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '잡화',
    },
    {
      dispCtgZoneId: '5410000002',
      dispCtgId: null,
      dispCtgNm: '뷰티X먼데이문',
      dispCtgEnNm: 'Monday Moon',
      dispCtgZhNm: 'Monday Moon',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072814443183038628520962_559.jpg',
      linkUrl: 'http://m.ssg.com/monm/main.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '뷰티X먼데이문',
    },
    {
      dispCtgZoneId: '5410000006',
      dispCtgId: null,
      dispCtgNm: '스포츠',
      dispCtgEnNm: 'Sports',
      dispCtgZhNm: '运动',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072114401652224140854414_993.jpg',
      linkUrl: 'http://m.ssg.com/page/llcategory/5410000006.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '스포츠',
    },
    {
      dispCtgZoneId: '5410000003',
      dispCtgId: null,
      dispCtgNm: '생활/주방',
      dispCtgEnNm: 'Home/Office',
      dispCtgZhNm: '家务/文具',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202105/2021052613443583524988100598_583.jpg',
      linkUrl: 'http://m.ssg.com/page/llcategory/5410000003.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '생활/주방',
    },
    {
      dispCtgZoneId: '1000015890',
      dispCtgId: null,
      dispCtgNm: '가구/인테리어',
      dispCtgEnNm: 'Furniture/Kitchen',
      dispCtgZhNm: '家具/厨房',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072114435685703321603332_446.jpg',
      linkUrl: 'http://m.ssg.com/page/llcategory/1000015890.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '가구/인테리어',
    },
    {
      dispCtgZoneId: '5410000004',
      dispCtgId: null,
      dispCtgNm: '유아동',
      dispCtgEnNm: 'Baby',
      dispCtgZhNm: '幼儿',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202101/2021011217133503520801144080_582.jpg',
      linkUrl: 'http://m.ssg.com/bpage/ssgbaby/main.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '유아동',
    },
    {
      dispCtgZoneId: '5410000005',
      dispCtgId: null,
      dispCtgNm: '디지털',
      dispCtgEnNm: 'Digital ',
      dispCtgZhNm: '数码',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072114443838883514790451_300.jpg',
      linkUrl: 'http://m.ssg.com/page/llcategory/5410000005.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '디지털',
    },
    {
      dispCtgZoneId: '1000015889',
      dispCtgId: null,
      dispCtgNm: '도서/e쿠폰/취미',
      dispCtgEnNm: 'E Coupons/Hobby',
      dispCtgZhNm: 'e优惠券/嗜好',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072114450966500216323021_114.jpg',
      linkUrl: 'http://m.ssg.com/page/llcategory/1000015889.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '도서/e쿠폰/취미',
    },
    {
      dispCtgZoneId: '5410000007',
      dispCtgId: null,
      dispCtgNm: '신선식품',
      dispCtgEnNm: 'Fresh Food',
      dispCtgZhNm: '新鲜食品',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072114452932964016659401_625.jpg',
      linkUrl: 'http://m.ssg.com/page/llcategory/5410000007.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '신선식품',
    },
    {
      dispCtgZoneId: '1000015925',
      dispCtgId: null,
      dispCtgNm: '가공/건강식품',
      dispCtgEnNm: 'Processed Food',
      dispCtgZhNm: '加工/保健食品',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072114460463206750262675_650.jpg',
      linkUrl: 'http://m.ssg.com/page/llcategory/1000015925.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '가공/건강식품',
    },
    {
      dispCtgZoneId: '1000016140',
      dispCtgId: null,
      dispCtgNm: '반려동물',
      dispCtgEnNm: null,
      dispCtgZhNm: null,
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202107/2021070910450361778749775974_701.jpg',
      linkUrl: 'http://m.ssg.com/page/llcategory/1000016140.ssg',
      siteNo: null,
      dispCtgShopTypeCd: '20',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: null,
      i18nDispCtgNm: '반려동물',
    },
  ],
};

export const emartData = {
  shopBannerList: [
    {
      id: '2002662591',
      title: '전단행사',
      desc: '전단행사',
      lnkdUrl: 'http://m.emart.ssg.com/plan/flyerPlanShop.ssg?app_banrId=2002662591',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015294791455893792689_59.png',
      strtDts: '20210603000000',
      endDts: '99991231235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '1',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '전단행사',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002296976',
      title: '오늘뭐먹지',
      desc: '오늘뭐먹지',
      lnkdUrl: 'http://m.emart.ssg.com/todaysFood.ssg?app_banrId=2002296976',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015301371077886104888_748.png',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '3',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '오늘뭐먹지',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002296984',
      title: '청소연구소',
      desc: '청소연구소',
      lnkdUrl:
        'http://m.emart.ssg.com/item/itemView.ssg?itemId=1000039028497&app_banrId=2002296984',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015302028697006537800_811.png',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '4',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '청소연구소',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002296978',
      title: '오늘은e요리',
      desc: '오늘은e요리',
      lnkdUrl: 'http://m.emart.ssg.com/recipe/trecipeMain.ssg?app_banrId=2002296978',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015302599199813016091_737.png',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '5',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '오늘은 e요리',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002296995',
      title: '이벤트',
      desc: '이벤트',
      lnkdUrl: 'http://m.emart.ssg.com/event/eventMain.ssg?app_banrId=2002296995',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015303044473107216410_848.png',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '6',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '이벤트',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002296991',
      title: '신상품',
      desc: '신상품',
      lnkdUrl: 'http://m.emart.ssg.com/page/newarrival.ssg?app_banrId=2002296991',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015303660584999565599_961.png',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '7',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '신상품',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002662594',
      title: '하나더',
      desc: '하나더',
      lnkdUrl:
        'http://m.emart.ssg.com/page/obanjang.ssg?subPageId=100000000006&app_banrId=2002662594',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015304142586686875768_352.png',
      strtDts: '20210503000000',
      endDts: '99991231235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '8',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '하나더',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
    {
      id: '2002662596',
      title: '인기세일',
      desc: '인기세일',
      lnkdUrl:
        'http://m.emart.ssg.com/page/obanjang.ssg?subPageId=100000000003&app_banrId=2002662596',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202106/2021063015305831702926077292_666.png',
      strtDts: '20210503000000',
      endDts: '99991231235959',
      maiTitleNm1: '',
      maiTitleNm2: '',
      subtitlNm1: '',
      subtitlNm2: '',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '244',
      imgHeight: '244',
      dispOrdr: '9',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '인기세일',
      modDts: '',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
  ],
  siteNo: '6001',
  specailBrandBannerList: [],
  killerBannerList: [
    {
      id: '2002297088',
      title: '먼데이문',
      desc: '먼데이문',
      lnkdUrl: 'http://m.ssg.com/monm/main.ssg?app_banrId=2002297088',
      lnkdType: '10',
      imgFileNm: 'http://ui.ssgcdn.com/cmpt/banner/202007/2020072715053504093125091412_215.jpg',
      strtDts: '20200723000000',
      endDts: '20510723235959',
      maiTitleNm1: 'MONDAY MOON',
      maiTitleNm2: '',
      subtitlNm1: '체험단 혜택부터 리얼 리뷰까지,',
      subtitlNm2: '새로운 뷰티를 만나다.',
      iconTgtLst: '',
      titleShadUseYn: '',
      imgWidth: '580',
      imgHeight: '348',
      dispOrdr: '0',
      bakgrndColrCdVal: '',
      banrRplcTextNm: '먼데이문',
      modDts: '20200723185119',
      advertYn: '',
      newYn: '',
      advertAcctId: '',
      advertBidId: '',
      advertBilngTypeCd: '',
      advertKindCd: '',
      advertExtensTeryDivCd: '',
      iconTgtList: [],
    },
  ],
  themeShopGrid: {
    unitType: 'QUICK_GRID_BANNER',
    reactPrefix: '카테고리_LNB|공식스토어|',
    maiTitleNm1: '공식스토어',
    maiTitleNm2: '전체보기',
    hasNext: 'false',
    lnkdUrl: 'http://m.emart.ssg.com/special/index.ssg',
    pageId: '',
    optionTypes: [],
    banrList: [
      {
        id: '',
        title: '노브랜드',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/nobrand/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070517084893210955207095_101.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '피코크',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/ssgpeacock/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070517090299932787088278_528.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'DAIZ',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/daiz2/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070517092432922399257239_973.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '앳홈',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/athome/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202012/2020121709343333281750158375_55.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '자주',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/newjaju/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202104/2021040916144250785816301681_282.jpg',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'ELECTROMART',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/electromart2/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070517094451288174923917_907.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'ASTORE',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/a-store/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202103/2021032213020824291653552265_835.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'LEGO',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/legostore/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201909/2019090518350576405664465566_446.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'SSG MEAL KIT',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/ssgmealkit/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202103/2021030416294953644389391538_375.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'Molly`s (몰리스)',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/mollynew/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202107/2021071513510220585313131631_938.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '스타벅스 앳 홈',
        desc: '',
        lnkdUrl:
          'http://m.emart.ssg.com/specialStore/starbucksathome/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070908572576347180371918_462.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '쓱찬',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/ssg-chan/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201907/2019070908574369792111984311_464.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '토이킹덤',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/toy-kingdom/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202101/2021012217184979746203998620_59.jpg',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: 'WINE & LIQUOR',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/wineliquor/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202006/2020062213083563013035599303_794.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
      {
        id: '',
        title: '한우전문관',
        desc: '',
        lnkdUrl: 'http://m.emart.ssg.com/specialStore/hanushop/main.ssg?tarea=store6001ssgdot',
        lnkdType: '10',
        imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/201909/2019092514290961130368459036_865.png',
        strtDts: '',
        endDts: '',
        maiTitleNm1: '',
        maiTitleNm2: '',
        subtitlNm1: '',
        subtitlNm2: '',
        iconTgtLst: '',
        titleShadUseYn: '',
        imgWidth: '0',
        imgHeight: '0',
        dispOrdr: '',
        bakgrndColrCdVal: '',
        banrRplcTextNm: '',
        modDts: '',
        advertYn: 'N',
        newYn: 'N',
        advertAcctId: '',
        advertBidId: '',
        advertBilngTypeCd: '',
        advertKindCd: '',
        advertExtensTeryDivCd: '',
        iconTgtList: [],
      },
    ],
    pageCmptId: '',
  },
  ctgList: [
    {
      dispCtgZoneId: null,
      dispCtgId: null,
      dispCtgNm: 'FOOD',
      dispCtgEnNm: 'Food',
      dispCtgZhNm: 'FOOD',
      imgFileNm: null,
      linkUrl: null,
      siteNo: '',
      dispCtgShopTypeCd: '40',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: [
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095739',
          dispCtgNm: '과일',
          dispCtgEnNm: 'Fruit',
          dispCtgZhNm: '水果',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072416394637492666161366_660.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095739',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '과일',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095740',
          dispCtgNm: '채소',
          dispCtgEnNm: 'Vegetable',
          dispCtgZhNm: '蔬菜',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072416400882453850567385_437.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095740',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '채소',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095498',
          dispCtgNm: '쌀/잡곡/견과',
          dispCtgEnNm: 'Rice/grains/nuts',
          dispCtgZhNm: '大米/谷物/坚果',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072411225008361663789166_561.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095498',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '쌀/잡곡/견과',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095499',
          dispCtgNm: '정육/계란류',
          dispCtgEnNm: 'Meat/eggs Ryu',
          dispCtgZhNm: '肉/蛋龙',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072411250875257629037762_198.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095499',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '정육/계란류',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095500',
          dispCtgNm: '수산물/건해산',
          dispCtgEnNm: 'Fisheries/construction Dissolution',
          dispCtgZhNm: '渔业/建筑业解散',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072411252737302607872260_602.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095500',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '수산물/건해산',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095501',
          dispCtgNm: '우유/유제품/\n유아식',
          dispCtgEnNm: 'Milk/dairy Products/baby Food',
          dispCtgZhNm: '牛奶/乳制品/婴幼儿食品',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072411254516940741507074_763.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095501',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '우유/유제품/\n유아식',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095502',
          dispCtgNm: '냉장/냉동/\n간편식',
          dispCtgEnNm: 'Chilled/frozen/ganpyeonsik',
          dispCtgZhNm: '冷藏/冷冻/ganpyeonsik',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413224386149173717917_117.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095502',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '냉장/냉동/\n간편식',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095503',
          dispCtgNm: '밀키트/김치/\n반찬',
          dispCtgEnNm: 'Wheat Kit/Kimchi/a Side Dish',
          dispCtgZhNm: '小麦试剂盒/辛奇/配菜',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202010/2020101409570168305090182509_232.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095503',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '밀키트/김치/\n반찬',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095507',
          dispCtgNm: '생수/음료/주류',
          dispCtgEnNm: 'Bottled Water And Beverages/alcoholic Beverages',
          dispCtgZhNm: '瓶装水和饮料/酒精饮料',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413233962435135746513_336.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095507',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '생수/음료/주류',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095508',
          dispCtgNm: '커피/원두/차',
          dispCtgEnNm: 'Coffee/coffee/tea',
          dispCtgZhNm: '咖啡/咖啡/茶',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413240441105563332556_913.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095508',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '커피/원두/차',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095504',
          dispCtgNm: '라면/면류/\n즉석식품/통조림',
          dispCtgEnNm: 'Ramen/noodles/instant Foods/canned',
          dispCtgZhNm: '拉面/面条/方便食品/罐头',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202010/2020101409574194452467238246_663.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095504',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '라면/면류/\n즉석식품/통조림',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095509',
          dispCtgNm: '장류/양념/\n가루/오일',
          dispCtgEnNm: 'Sauces/condiments/flour/oil',
          dispCtgZhNm: '酱料/调味品/面粉/油',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413243878102303223230_433.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095509',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '장류/양념/\n가루/오일',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095505',
          dispCtgNm: '과자/시리얼/\n빙과/떡',
          dispCtgEnNm: 'Sweets/cereals/ice Cream/bread/',
          dispCtgZhNm: '糖果/谷物/冰淇淋/面包/',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413250273602283462228_638.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095505',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '과자/시리얼/\n빙과/떡',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095506',
          dispCtgNm: '베이커리/잼/\n샐러드',
          dispCtgEnNm: 'Bakery/jam/salad',
          dispCtgZhNm: '面包/果酱/沙拉',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413252445694576691557_655.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095506',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '베이커리/잼/\n샐러드',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095510',
          dispCtgNm: '건강식품',
          dispCtgEnNm: 'Health Food',
          dispCtgZhNm: '保健食品',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413254023844910058491_612.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095510',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '건강식품',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000095511',
          dispCtgNm: '친환경/유기농',
          dispCtgEnNm: 'Eco-friendly/organic',
          dispCtgZhNm: '环保/有机',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413255326187546460854_769.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000095511',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '60',
          textColrCdVal: '#5d30ff',
          ctgList: null,
          i18nDispCtgNm: '친환경/유기농',
        },
        {
          dispCtgZoneId: '1000015749',
          dispCtgId: '6000163135',
          dispCtgNm: '손질/소포장',
          dispCtgEnNm: 'Trimmed/Small Packaging',
          dispCtgZhNm: '修剪/小包装',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202011/2020112413340647085755821675_944.jpg',
          linkUrl: 'http://m.emart.ssg.com/page/single.ssg?mGnbYn=N',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '60',
          textColrCdVal: '#5d30ff',
          ctgList: null,
          i18nDispCtgNm: '손질/소포장',
        },
      ],
      i18nDispCtgNm: 'FOOD',
    },
    {
      dispCtgZoneId: null,
      dispCtgId: null,
      dispCtgNm: 'LIFE',
      dispCtgEnNm: 'Life',
      dispCtgZhNm: 'LIFE',
      imgFileNm: null,
      linkUrl: null,
      siteNo: '',
      dispCtgShopTypeCd: '40',
      dispCtgTypeCd: null,
      textColrCdVal: '#444444',
      ctgList: [
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '6000180225',
          dispCtgNm: '세탁/청소/\n욕실/생활용품',
          dispCtgEnNm: 'Washing/cleaning/bathroom And Household Goods',
          dispCtgZhNm: '洗涤/清洁/浴室和家庭用品',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202105/2021052613483185646829886682_548.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000180225',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '세탁/청소/\n욕실/생활용품',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '6000178087',
          dispCtgNm: '침구/가구/\n홈인테리어',
          dispCtgEnNm: 'Bedding/furniture/home Decor',
          dispCtgZhNm: '床上用品/家具/家居装饰',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202105/2021051313095320296760323776_268.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000178087',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '침구/가구/\n홈인테리어',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '6000180234',
          dispCtgNm: '제지/위생/\n건강용품',
          dispCtgEnNm: 'Paper/sanitation/health Supplies',
          dispCtgZhNm: '纸/卫生/保健用品',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202105/2021051313064769618377415837_431.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000180234',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '제지/위생/\n건강용품',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '6000180226',
          dispCtgNm: '주방용품',
          dispCtgEnNm: 'Kitchen Utensils',
          dispCtgZhNm: '厨具',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202105/2021051313091042765577920657_724.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000180226',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '주방용품',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '6000180228',
          dispCtgNm: '생활잡화/공구',
          dispCtgEnNm: 'Household Goods/tools',
          dispCtgZhNm: '家居用品/工具',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202105/2021051317143830834039997403_165.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000180228',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '생활잡화/공구',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '6000185244',
          dispCtgNm: '반려동물',
          dispCtgEnNm: null,
          dispCtgZhNm: null,
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202107/2021071614324562934721207472_771.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000185244',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '반려동물',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '0006520000',
          dispCtgNm: '뷰티',
          dispCtgEnNm: 'Beauty',
          dispCtgZhNm: '美容',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413280603790614403161_396.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=0006520000',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '뷰티',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '6000163146',
          dispCtgNm: '유아동/출산/\n완구',
          dispCtgEnNm: 'Baby & Child/maternity/toys',
          dispCtgZhNm: '婴幼儿/孕产妇/玩具',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202011/2020110610003300996007924700_892.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000163146',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '유아동/출산/\n완구',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '6000014364',
          dispCtgNm: '패션의류/\n언더웨어',
          dispCtgEnNm: 'Fashion Apparel/Underwear',
          dispCtgZhNm: '时尚服饰/内衣',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413295016884369552536_429.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000014364',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '패션의류/\n언더웨어',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '6000013960',
          dispCtgNm: '잡화/슈즈/명품',
          dispCtgEnNm: 'Miscellaneous/Luxury Goods',
          dispCtgZhNm: '杂货/鞋/名牌',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413302832530907695090_557.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=6000013960',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '잡화/슈즈/명품',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '0006570000',
          dispCtgNm: '스포츠/레저/\n여행/자동차',
          dispCtgEnNm: 'Sports/Leisure/Travel/Cars',
          dispCtgZhNm: '运动/休闲/旅行/汽车',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413304098730659765065_588.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=0006570000',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '스포츠/레저/\n여행/자동차',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '0006580000',
          dispCtgNm: '컴퓨터/가전/\n디지털/렌탈',
          dispCtgEnNm: 'Computer/Electronics/Digital/Rental',
          dispCtgZhNm: '电脑/家电/数码/租赁',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413305479939763096976_305.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=0006580000',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '컴퓨터/가전/\n디지털/렌탈',
        },
        {
          dispCtgZoneId: '1000015750',
          dispCtgId: '0006590000',
          dispCtgNm: '문구/취미/도서',
          dispCtgEnNm: 'Stationary/Hobbies/Books/Pet Supplies',
          dispCtgZhNm: '文具/兴趣/图书/伴侣用品',
          imgFileNm: 'http://ui.ssgcdn.com/cmpt/ctg/202007/2020072413313435567772329777_829.jpg',
          linkUrl: 'http://m.emart.ssg.com/disp/category.ssg?dispCtgId=0006590000',
          siteNo: null,
          dispCtgShopTypeCd: '10',
          dispCtgTypeCd: '10',
          textColrCdVal: '#444444',
          ctgList: null,
          i18nDispCtgNm: '문구/취미/도서',
        },
      ],
      i18nDispCtgNm: 'LIFE',
    },
  ],
};
