export const mallList = [
  {
    siteNo: '6005',
    href: 'm.ssg.com',
    siteNm: 'SSG.COM',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '6001',
    href: 'm.emart.ssg.com',
    siteNm: '이마트몰',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '6004',
    href: 'm.shinsegaemall.ssg.com',
    siteNm: '신세계몰',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '6002',
    href: 'm.traders.ssg.com',
    siteNm: '트레이더스',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '6009',
    href: 'm.shinsegaemall.ssg.com/dept/main.ssg',
    siteNm: '신세계백화점',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '7009',
    href: 'm.earlymorning.ssg.com',
    siteNm: '새벽배송',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '7011',
    href: 'm.casamia.ssg.com',
    siteNm: '까사미아',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '7015',
    href: 'm.starbucks.ssg.com',
    siteNm: 'STARBUCKS',
    needOpenIcon: 'Y',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '7012',
    href: 'm.chicor.ssg.com',
    siteNm: 'CHICOR',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '6200',
    href: 'm.tv.ssg.com',
    siteNm: '신세계TV쇼핑',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '6100',
    href: 'm.howdy.ssg.com',
    siteNm: 'howdy',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '7013',
    href: 'm.triip.ssg.com',
    siteNm: '여행',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '6300',
    href: 'm.sivillage.ssg.com',
    siteNm: 'S.I.VILLAGE',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '6400',
    href: 'm.starfield.ssg.com',
    siteNm: '스타필드',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '7008',
    href: 'm.premiumoutlets.ssg.com',
    siteNm: '프리미엄아울렛',
    needOpenIcon: 'N',
    adInfo: {
      mallMvmtLogoImgUrl: '',
      linkUrl: '',
      gnbTopLogoImgUrl: '',
      endDts: '',
    },
  },
  {
    siteNo: '6004_10_lg01',
    href: 'm.shinsegaemall.ssg.com/specialStore/dior/main.ssg',
    siteNm: 'LG전자',
    needOpenIcon: 'Y',
    adInfo: {
      mallMvmtLogoImgUrl:
        'http://static.ssgcdn.com/cmpt/gnb/202109/0000000031_2021090908342389475770941677_438.png',
      linkUrl: 'http://m.shinsegaemall.ssg.com/specialStore/lg01/main.ssg',
      gnbTopLogoImgUrl:
        'http://static.ssgcdn.com/cmpt/gnb/202109/0000000031_2021090908341951114361574436_677.png',
      endDts: '20211003235959',
    },
  },
];

export const userInfo = {
  bnSaleStrNo: '2451',
  birthday: '',
  userNm: '',
  cartNm: '장바구니',
  ckWhere: 'direct_ssg',
  emSaleStrNo: '2034',
  mbrType: 'B2C',
  gmSaleStrNo: '2449',
  mbrTypeCd: '',
  shpplocMod: 'MY',
  dmId: '',
  shipZipCd: '04781',
  isLoginYn: 'N',
  vvipYn: 'N',
  mbrcoId: '000000',
  trSaleStrNo: '2154',
  gmSaleStrYn: 'N',
  mbrGrdCd: '',
  countryCode: 'N/A',
  emplYn: 'N',
  shpplocModKey: '',
  ga: '00',
  emRsvtShppPsblYn: 'Y',
  mbrcoNm: '',
};

export const navBarData = [
  {
    menuDispNm: '홈',
    menuType: 'template',
    trackingNm: '',
    menuID: '100000000017',
    pathName: 'home',
    isNewIcon: false,
  },
  {
    menuDispNm: '특가',
    menuType: 'template',
    trackingNm: '',
    menuID: '100000000340',
    pathName: 'SpecialPrice',
    isNewIcon: false,
  },
  {
    menuDispNm: '랭킹',
    menuType: 'template',
    trackingNm: '',
    menuID: '100000000009',
    pathName: 'ranking',
    isNewIcon: false,
  },
  {
    menuDispNm: 'SSG.LIVE',
    menuType: 'template',
    trackingNm: '',
    menuID: '100000000322',
    pathName: 'ssglive',
    isNewIcon: false,
  },
  {
    menuDispNm: '브랜드',
    menuType: 'template',
    trackingNm: '',
    menuID: '100000000700',
    pathName: 'Brandindex',
    isNewIcon: false,
  },
  {
    menuDispNm: '추석선물세트',
    menuType: 'special_store',
    trackingNm: '',
    menuID: 'giftshopssg',
    pathName: 'test',
    isNewIcon: true,
  },
];

export const liveCommerceFloatInfo = {
  brocStrtDts: '2021/10/06 20:00:00',
  brocEndDts: '2021/10/06 21:00:59',
  totalCnt: 2,
  liveLayerApiUrl: 'http://stg-m.apps.ssg.com/api/ssglive/liveLayer.ssg',
  liveFloatImgUrl:
    'http://img.ssgcdn.com/trans.ssg?src=/cmpt/banner/202109/2021092918344960933369747336_637.jpg&t=b56f8c00d9891d882bd655cdad9d1491e450e86d',
  liveFloatSmallImgUrl:
    'http://img.ssgcdn.com/trans.ssg?src=/cmpt/banner/202109/2021092918344960933369747336_637.jpg&w=88&h=110&edit=c&t=e46e044c90b97e72f22ab6f2964833167d716583',
  livePageLinkUrl: 'http://stg-m.ssg.com/liveCommerce?reservationId=8dejr143pzn2vgn4',
};
export const chatInfo = {
  csTalkCount: 100,
  csTalkHref: '#',
  sellerTalkCount: 1,
  sellerTalkHref: '#',
};
