export const categoryDummyData = [
  {
    dataType: 'SPECIALPRICE_SSG',
    hasFixedLayer: 'true',
    dispCtgList: [
      {
        dispCtgId: '',
        cornrSetId: '',
        dispCtgNm: '전체',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'true',
        isEnabled: 'false',
      },
      {
        dispCtgId: '5410000001',
        cornrSetId: '',
        dispCtgNm: '패션',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '1000015891',
        cornrSetId: '',
        dispCtgNm: '잡화',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '5410000002',
        cornrSetId: '',
        dispCtgNm: '뷰티',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '5410000006',
        cornrSetId: '',
        dispCtgNm: '스포츠',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '5410000003',
        cornrSetId: '',
        dispCtgNm: '생활/주방',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '1000015890',
        cornrSetId: '',
        dispCtgNm: '가구/인테리어',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '5410000004',
        cornrSetId: '',
        dispCtgNm: '유아동',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '5410000005',
        cornrSetId: '',
        dispCtgNm: '디지털',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '1000015889',
        cornrSetId: '',
        dispCtgNm: '도서/e쿠폰/취미',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '5410000007',
        cornrSetId: '',
        dispCtgNm: '신선식품',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '1000015925',
        cornrSetId: '',
        dispCtgNm: '가공/건강식품',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
      {
        dispCtgId: '1000016140',
        cornrSetId: '',
        dispCtgNm: '반려동물',
        dispCtgDesc: '',
        imgFileNm: 'http://ui.ssgcdn.com',
        onImgFileNm: 'http://ui.ssgcdn.com',
        bakgrndColrCdVal: '',
        isActivated: 'false',
        isEnabled: 'false',
      },
    ],
    pageId: '100000000019',
    tareaCd: '100000000019_2_2',
    unitType: 'CATEGORY_TAB',
    hasLayerFix: 'true',
    pageSetId: '2',
    reactPrefix: '특가|특가 카테고리바|',
    apiUrl: 'http://stg-m.apps.ssg.com/api/page/area/datas.ssg',
    hasEndless: 'true',
    hasMorePage: 'true',
    pageCmptId: '2',
  },
];
